[providers]
providers = ["node"]

[pkgs]
pkgs = [
  "chromium",
  "nss",
  "atk",
  "cups",
  "libXcomposite",
  "libXcursor",
  "libXdamage",
  "libXext",
  "libXi",
  "libXrandr",
  "libXScrnSaver",
  "libXtst",
  "pango",
  "at-spi2-atk"
]
